# Numpy Random

# Introduction

NumPy is the fundamental libray for scientific computing with Python. The random package found in the Numpy library and is mainly used for generating random data. The package is broken down into four sections:

- Simple random data
- Permutations
- Distributions
- Random generator

This notebook will be divided into four sections based on these headings, showing and explaining examples of functions in eachof these sections.

To use the numpy.random package, the library must be imported like so:

In [ ]:
import numpy as np

# Simple Random Data

There are many functions in this part of the Numpy.random package. Such as:
   - rand
   - randn
   - randint
   - random_integers
   - random_sample
   - random
   - ranf
   - sample
   - choice
   - bytes
This notebook will contain examples of a few of these functions.

# Example 1- numpy.ramdom.rand

This creates an Array of the given shape and populates it with random samples.

In [4]:
# Import numpy for random package
import numpy as np
# Generate our random numbers
np.random.rand(2,7,4)

array([[[0.25803112, 0.44974468, 0.28630916, 0.56378454],
        [0.66944059, 0.22903839, 0.98778406, 0.19052568],
        [0.49463161, 0.98639229, 0.78913377, 0.73002523],
        [0.69761412, 0.96243894, 0.53311839, 0.94013564],
        [0.85725594, 0.3756662 , 0.88654351, 0.2290743 ],
        [0.23613383, 0.45545684, 0.78461634, 0.4874203 ],
        [0.76057669, 0.38621063, 0.81778056, 0.22329791]],

       [[0.84076809, 0.29225731, 0.59013607, 0.71338896],
        [0.37133971, 0.05267921, 0.71014707, 0.76144098],
        [0.6682191 , 0.74581523, 0.9426667 , 0.47078517],
        [0.38326361, 0.35662842, 0.43736121, 0.36344545],
        [0.52787138, 0.66884129, 0.50631501, 0.07234445],
        [0.32717569, 0.53119977, 0.28292833, 0.61705114],
        [0.81403012, 0.57477868, 0.88988001, 0.36684279]]])

# Example 2- numpy.ramdom.randn

This returns a sample/samples from the “standard normal” distribution.

In [7]:
# Import numpy for random package
import numpy as np

# Generate our random numbers
np.random.randn(2,7,4)

array([[[-1.46501911, -0.76762712, -1.14985006,  0.27317362],
        [ 0.89499989, -1.35529308, -0.74808713,  0.07408884],
        [-0.18273017, -0.01221952,  0.20517585, -2.18579717],
        [-1.00156339,  1.3538111 , -0.27467332,  1.13114814],
        [-0.20693101, -1.34515277, -1.58489019, -1.59012264],
        [ 0.17471893,  0.11941868, -0.10388937, -0.23568347],
        [ 1.95085612,  0.51777826,  0.63145044,  0.63843163]],

       [[-1.14121328,  1.34928532, -0.64820457, -0.83556523],
        [-0.10100146,  0.5436473 ,  0.55137074, -0.18335567],
        [ 0.76983497, -0.53357292,  0.5395786 ,  0.00474634],
        [ 0.43943037,  0.30189029,  1.23809062, -0.15800626],
        [ 0.35296021, -0.0933913 , -0.58626067,  0.11224804],
        [-1.9666799 ,  0.30782776, -0.19639514,  0.65910858],
        [-1.4857614 ,  1.14557243,  0.14032117, -1.07505449]]])

# Example 3- numpy.ramdom.randint

This returns a random integer from low to high, where it is optional to state the size of the array returned, the default is 1.

In [5]:
# Generate a random integer between 3 and 9
np.random.randint(3,9)

7

In [6]:
# Generate an array of 4 elements with random integers between 3 and 18
np.random.randint(3,18,size=4)

array([ 5,  6, 10,  5])